# Generated by Django 6.0.3 on 2026-04-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinrequest',
            old_name='hashed_password',
            new_name='raw_password',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='company.agency'),
        ),
    ]
