# Generated by Django 6.0.3 on 2026-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lord', 'Lord'), ('owner', 'Owner'), ('admin', 'Admin'), ('supervisor', 'Supervisor'), ('guard', 'Guard')], default='owner', max_length=20),
        ),
    ]
