# Generated by Django 6.0.3 on 2026-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lord', 'Lord'), ('owner', 'Owner'), ('admin', 'Admin'), ('supervisor', 'Supervisor'), ('guard', 'Guard'), ('client', 'Site Client')], default='owner', max_length=20),
        ),
    ]
