# Generated by Django 6.0.3 on 2026-04-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='transaction_limit',
            field=models.DecimalField(decimal_places=2, default=2000000, max_digits=14),
        ),
    ]
