# Generated by Django 6.0.3 on 2026-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_banktransaction_salary_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='running_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
