# Generated by Django 6.0.3 on 2026-04-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_banktransaction_running_balance'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='billing.bankaccount'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('cash', 'Cash')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('give_guard', 'Given to Guard'), ('give_supervisor', 'Given to Supervisor'), ('fuel', 'Fuel Stop'), ('salary_deduct', 'Salary Advance Deduction'), ('transfer_in', 'Transfer Received'), ('transfer_out', 'Transfer Sent')], max_length=30),
        ),
    ]
