# Generated by Django 6.0.3 on 2026-04-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_siteshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guards', to='company.siteshift'),
        ),
    ]
