# Generated by Django 6.0.3 on 2026-04-05 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_wages', to='company.agency')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_wages', to='company.guard')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.site')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('guard', 'site', 'date')},
            },
        ),
    ]
