# Generated by Django 6.0.3 on 2026-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_dailywage'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
