# Generated by Django 6.0.3 on 2026-04-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_guard_advance_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='client_account_name',
            field=models.CharField(blank=True, help_text="Client's sending bank account details", max_length=150),
        ),
        migrations.AlterField(
            model_name='site',
            name='bill_account_name',
            field=models.CharField(blank=True, help_text="Owner's receiving bank account name", max_length=150),
        ),
    ]
