# Generated by Django 6.0.3 on 2026-04-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_site_client_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='agency',
            name='invoice_prefix',
            field=models.CharField(default='2026-27/', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='site',
            name='client_gstin',
            field=models.CharField(blank=True, help_text="Client's GST number", max_length=15),
        ),
        migrations.AddField(
            model_name='site',
            name='invoice_format',
            field=models.CharField(choices=[('normal', 'Normal Invoice'), ('gst', 'GST Invoice')], default='normal', max_length=10),
        ),
    ]
