# Generated by Django 6.0.3 on 2026-04-06 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_agency_gstin_agency_invoice_prefix_agency_pan_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='client_user',
            field=models.ForeignKey(blank=True, help_text="The login account for the client's Dashboard", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
