# Generated by Django 6.0.3 on 2026-04-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_site_client_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('guard', 'date', 'shift')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='True if this is an extra/second shift on the same day'),
        ),
    ]
