# Generated by Django 6.0.3 on 2026-04-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_attendance_multi_shift_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='account_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='guard',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='guard',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guard',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
