# Generated by Django 6.0.3 on 2026-04-02 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_days', models.PositiveIntegerField()),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('days_half', models.PositiveIntegerField(default=0)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_given', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('online', 'Online Transfer'), ('offline', 'Cash / Offline')], max_length=10, null=True)),
                ('to_account_details', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments', to='billing.bankaccount')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='company.guard')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('guard', 'month', 'year')},
            },
        ),
    ]
