# Generated by Django 6.0.3 on 2026-04-02 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('travelling', 'Travelling'), ('reached', 'Reached / On Site'), ('visited', 'Visited / Done'), ('skipped', 'Skipped')], default='assigned', max_length=20)),
                ('depart_time', models.DateTimeField(blank=True, null=True)),
                ('arrive_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='company.site')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assigned_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('info', 'Information / Update'), ('complaint', 'Complaint'), ('urgent', 'Urgent'), ('other', 'Other')], default='info', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='supervisor.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.OneToOneField(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
